delete from drafts;
insert into `drafts` values ('Belloche', 1, 'testDraft', 'this is a test', 5, 0,
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jets', 'Justin Fields', 'QB', 'Ohio State',
                             'Dolphins', 'Penei Sowell', 'OT', 'Oregon',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson',
                             'Jaguars', 'Trevor Lawrence', 'QB', 'Clemson'
                            );